class ACE_Medical_Treatment_Actions {
    class Morphine;

    class CLASS(cocaine): Morphine {
        displayName = CSTRING(Cocaine);
        displayNameProgress = CSTRING(CocaineProgress);
        icon = "z\ace\addons\medical_gui\ui\painkillers.paa";
        medicRequired = 0;
        allowedSelections[] = {"Head"};
        category = "medication";
        items[] = {QCLASS(cocaine)};
        treatmentLocations = 0;
        condition = QFUNC(medicationCondition);
        treatmentTime = 3;
        treatmentTimeTrained = 2;
        callbackSuccess = QFUNC(processMedication);
        animationMedic = "";
        animationMedicProne = "";
        animationMedicSelf = "";
        animationMedicSelfProne = "";
        sounds[] = {{QPATHTOEF(audio,sounds\items\sniff.ogg), 1, 1, 50}};
        litter[] = {};
    };

    class CLASS(antibiotic): Morphine {
        displayName = CSTRING(Antibiotic);
        displayNameProgress = CSTRING(AntibioticProgress);
        icon = "z\ace\addons\medical_gui\ui\painkillers.paa";
        medicRequired = 0;
        allowedSelections[] = {"Head"};
        category = "medication";
        consumeItem = 0;
        items[] = {QCLASS(antibiotic)};
        treatmentLocations = 0;
        condition = QFUNC(medicationCondition);
        treatmentTime = 5;
        treatmentTimeTrained = 3;
        callbackStart = QFUNC(processAnimation);
        callbackSuccess = QFUNC(processMedication);
        animationMedic = "";
        animationMedicProne = "";
        animationMedicSelf = "";
        animationMedicSelfProne = "";
        sounds[] = {{QPATHTOEF(audio,sounds\items\caffetinBoxOpen.ogg), 1, 1, 50}};
        litter[] = {};
    };

    class CLASS(antidote): Morphine {
        displayName = CSTRING(Antidote);
        displayNameProgress = CSTRING(AntidoteProgress);
        icon = "z\ace\addons\medical_gui\ui\auto_injector.paa";
        medicRequired = 0;
        allowedSelections[] = {"LeftArm", "RightArm", "LeftLeg", "RightLeg"};
        category = "medication";
        items[] = {QCLASS(antidote)};
        treatmentLocations = 0;
        condition = "";
        treatmentTime = 5;
        treatmentTimeTrained = 3;
        callbackSuccess = QFUNC(processMedication);
        // animationMedic = "AinvPknlMstpSlayWpstDnon_medicOther";
        // animationMedicProne = "";
        // animationMedicSelf = "AinvPknlMstpSlayWpstDnon_medic";
        // animationMedicSelfProne = "";
        sounds[] = {{"z\ace\addons\medical_treatment\sounds\Inject.ogg", 1, 1, 50}};
        litter[] = {{"MedicalGarbage_01_Injector_F"}};
    };

    class CLASS(antiparasitic): Morphine {
        displayName = CSTRING(Antiparasitic);
        displayNameProgress = CSTRING(AntiparasiticProgress);
        icon = "z\ace\addons\medical_gui\ui\painkillers.paa";
        medicRequired = 0;
        allowedSelections[] = {"Head"};
        category = "medication";
        consumeItem = 0;
        items[] = {QCLASS(antiparasitic)};
        treatmentLocations = 0;
        condition = QFUNC(medicationCondition);
        treatmentTime = 5;
        treatmentTimeTrained = 3;
        callbackStart = QFUNC(processAnimation);
        callbackSuccess = QFUNC(processMedication);
        animationMedic = "";
        animationMedicProne = "";
        animationMedicSelf = "";
        animationMedicSelfProne = "";
        sounds[] = {{QPATHTOEF(audio,sounds\items\caffetinBoxOpen.ogg), 1, 1, 50}};
        litter[] = {};
    };

    class CLASS(caffetin): Morphine {
        displayName = CSTRING(Caffetin);
        displayNameProgress = CSTRING(CaffetinProgress);
        icon = "z\ace\addons\medical_gui\ui\painkillers.paa";
        medicRequired = 0;
        allowedSelections[] = {"Head"};
        category = "medication";
        consumeItem = 0;
        items[] = {QCLASS(caffetin)};
        treatmentLocations = 0;
        condition = QFUNC(medicationCondition);
        treatmentTime = 5;
        treatmentTimeTrained = 3;
        callbackStart = QFUNC(processAnimation);
        callbackSuccess = QFUNC(processMedication);
        animationMedic = "";
        animationMedicProne = "";
        animationMedicSelf = "";
        animationMedicSelfProne = "";
        sounds[] = {{QPATHTOEF(audio,sounds\items\caffetinBoxOpen.ogg), 1, 1, 50}};
        litter[] = {};
    };

    class CLASS(caffeine): Morphine {
        displayName = CSTRING(Caffeine);
        displayNameProgress = CSTRING(CaffeineProgress);
        icon = "z\ace\addons\medical_gui\ui\painkillers.paa";
        medicRequired = 0;
        allowedSelections[] = {"Head"};
        category = "medication";
        consumeItem = 0;
        items[] = {QCLASS(caffeine)};
        treatmentLocations = 0;
        condition = QFUNC(medicationCondition);
        treatmentTime = 5;
        treatmentTimeTrained = 3;
        callbackStart = QFUNC(processAnimation);
        callbackSuccess = QFUNC(processMedication);
        animationMedic = "";
        animationMedicProne = "";
        animationMedicSelf = "";
        animationMedicSelfProne = "";
        sounds[] = {{QPATHTOEF(audio,sounds\items\crinklingPlastic.ogg), 1, 1, 50}};
        litter[] = {};
    };

    class CLASS(haloperidol): Morphine {
        displayName = CSTRING(Haloperidol);
        displayNameProgress = CSTRING(HaloperidolProgress);
        icon = "z\ace\addons\medical_gui\ui\auto_injector.paa";
        medicRequired = 0;
        allowedSelections[] = {"LeftArm", "RightArm", "LeftLeg", "RightLeg"};
        category = "medication";
        items[] = {QCLASS(haloperidol)};
        treatmentLocations = 0;
        condition = "";
        treatmentTime = 5;
        treatmentTimeTrained = 3;
        callbackSuccess = QFUNC(processMedication);
        // animationMedic = "AinvPknlMstpSlayWpstDnon_medicOther";
        // animationMedicProne = "";
        // animationMedicSelf = "AinvPknlMstpSlayWpstDnon_medic";
        // animationMedicSelfProne = "";
        sounds[] = {{"z\ace\addons\medical_treatment\sounds\Inject.ogg", 1, 1, 50}};
        litter[] = {{"MedicalGarbage_01_Injector_F"}};
    };

    class CLASS(clozapineBox): Morphine {
        displayName = CSTRING(ClozapineBox);
        displayNameProgress = CSTRING(ClozapineBoxProgress);
        icon = "z\ace\addons\medical_gui\ui\painkillers.paa";
        medicRequired = 0;
        allowedSelections[] = {"Head"};
        category = "medication";
        items[] = {QCLASS(clozapineBox)};
        treatmentLocations = 0;
        condition = QFUNC(medicationCondition);
        treatmentTime = 5;
        treatmentTimeTrained = 3;
        callbackStart = QFUNC(processAnimation);
        callbackSuccess = QFUNC(processMedication);
        animationMedic = "";
        animationMedicProne = "";
        animationMedicSelf = "";
        animationMedicSelfProne = "";
        sounds[] = {{QPATHTOEF(audio,sounds\items\caffetinBoxOpen.ogg), 1, 1, 50}};
        litter[] = {};
    };

    class CLASS(deconKit): Morphine {
        displayName = CSTRING(DeconKit);
        displayNameProgress = CSTRING(DeconKitProgress);
        icon = "z\ace\addons\medical_gui\ui\painkillers.paa";
        medicRequired = 0;
        allowedSelections[] = {"Body"};
        category = "advanced";
        items[] = {QCLASS(deconKit)};
        treatmentLocations = 0;
        condition = "";
        treatmentTime = 5;
        treatmentTimeTrained = 3;
        callbackStart = QFUNC(processAnimation);
        callbackSuccess = QFUNC(processMedication);
        animationMedic = "";
        animationMedicProne = "";
        animationMedicSelf = "";
        animationMedicSelfProne = "";
        sounds[] = {{QPATHTOEF(audio,sounds\items\caffetinBoxOpen.ogg), 1, 1, 50}};
        litter[] = {};
    };

    class CLASS(painkillers): Morphine {
        displayName = CSTRING(Painkillers);
        displayNameProgress = CSTRING(PainkillersProgress);
        icon = "z\ace\addons\medical_gui\ui\painkillers.paa";
        medicRequired = 0;
        allowedSelections[] = {"Head"};
        category = "medication";
        items[] = {QCLASS(painkillers)};
        treatmentLocations = 0;
        condition = QFUNC(medicationCondition);
        treatmentTime = 5;
        treatmentTimeTrained = 3;
        callbackStart = QFUNC(processAnimation);
        callbackSuccess = QFUNC(processMedication);
        animationMedic = "";
        animationMedicProne = "";
        animationMedicSelf = "";
        animationMedicSelfProne = "";
        sounds[] = {{QPATHTOEF(audio,sounds\items\caffetinBoxOpen.ogg), 1, 1, 50}};
        litter[] = {};
    };

    class CLASS(potassiumIodate): Morphine {
        displayName = CSTRING(PotassiumIodate);
        displayNameProgress = CSTRING(PotassiumIodateProgress);
        icon = "z\ace\addons\medical_gui\ui\painkillers.paa";
        medicRequired = 0;
        allowedSelections[] = {"Head"};
        category = "medication";
        items[] = {QCLASS(potassiumIodate)};
        treatmentLocations = 0;
        condition = QFUNC(medicationCondition);
        treatmentTime = 5;
        treatmentTimeTrained = 3;
        callbackStart = QFUNC(processAnimation);
        callbackSuccess = QFUNC(processMedication);
        animationMedic = "";
        animationMedicProne = "";
        animationMedicSelf = "";
        animationMedicSelfProne = "";
        sounds[] = {{QPATHTOEF(audio,sounds\items\pillBottleOpen.ogg), 1, 1, 50}};
        litter[] = {};
    };

    class CLASS(randomMedication): Morphine {
        displayName = CSTRING(RandomMedication);
        displayNameProgress = CSTRING(RandomMedicationProgress);
        icon = "z\ace\addons\medical_gui\ui\painkillers.paa";
        medicRequired = 0;
        allowedSelections[] = {"Head"};
        category = "medication";
        items[] = {QCLASS(randomMedication)};
        treatmentLocations = 0;
        condition = QFUNC(medicationCondition);
        treatmentTime = 5;
        treatmentTimeTrained = 3;
        callbackStart = QFUNC(processAnimation);
        callbackSuccess = QFUNC(processMedication);
        animationMedic = "";
        animationMedicProne = "";
        animationMedicSelf = "";
        animationMedicSelfProne = "";
        sounds[] = {{QPATHTOEF(audio,sounds\items\pillBottleOpen.ogg), 1, 1, 50}};
        litter[] = {};
    };

    class CLASS(sleepingPills): Morphine {
        displayName = CSTRING(SleepingPills);
        displayNameProgress = CSTRING(SleepingPillsProgress);
        icon = "z\ace\addons\medical_gui\ui\painkillers.paa";
        medicRequired = 0;
        allowedSelections[] = {"Head"};
        category = "medication";
        items[] = {QCLASS(sleepingPills)};
        treatmentLocations = 0;
        condition = QFUNC(medicationCondition);
        treatmentTime = 5;
        treatmentTimeTrained = 3;
        callbackStart = QFUNC(processAnimation);
        callbackSuccess = QFUNC(processMedication);
        animationMedic = "";
        animationMedicProne = "";
        animationMedicSelf = "";
        animationMedicSelfProne = "";
        sounds[] = {{QPATHTOEF(audio,sounds\items\pillBottleOpen.ogg), 1, 1, 50}};
        litter[] = {};
    };

    class CLASS(thrombomodulin): Morphine {
        displayName = CSTRING(Thrombomodulin);
        displayNameProgress = CSTRING(ThrombomodulinProgress);
        icon = "z\ace\addons\medical_gui\ui\auto_injector.paa";
        medicRequired = 0;
        allowedSelections[] = {"LeftArm", "RightArm", "LeftLeg", "RightLeg"};
        category = "medication";
        items[] = {QCLASS(thrombomodulin)};
        treatmentLocations = 0;
        condition = "";
        treatmentTime = 5;
        treatmentTimeTrained = 3;
        callbackSuccess = QFUNC(processMedication);
        // animationMedic = "AinvPknlMstpSlayWpstDnon_medicOther";
        // animationMedicProne = "";
        // animationMedicSelf = "AinvPknlMstpSlayWpstDnon_medic";
        // animationMedicSelfProne = "";
        sounds[] = {{"z\ace\addons\medical_treatment\sounds\Inject.ogg", 1, 1, 50}};
        litter[] = {{"MedicalGarbage_01_Injector_F"}};
    };

    class CLASS(thrombomodulin_Stimpack): Morphine {
        displayName = CSTRING(ThrombomodulinStim);
        displayNameProgress = CSTRING(ThrombomodulinStimProgress);
        icon = "z\ace\addons\medical_gui\ui\auto_injector.paa";
        medicRequired = 0;
        allowedSelections[] = {"LeftArm", "RightArm", "LeftLeg", "RightLeg"};
        category = "medication";
        items[] = {QCLASS(thrombomodulin_Stimpack)};
        treatmentLocations = 0;
        condition = "";
        treatmentTime = 5;
        treatmentTimeTrained = 3;
        callbackSuccess = QFUNC(processMedication);
        // animationMedic = "AinvPknlMstpSlayWpstDnon_medicOther";
        // animationMedicProne = "";
        // animationMedicSelf = "AinvPknlMstpSlayWpstDnon_medic";
        // animationMedicSelfProne = "";
        sounds[] = {{"z\ace\addons\medical_treatment\sounds\Inject.ogg", 1, 1, 50}};
        litter[] = {{"MedicalGarbage_01_Injector_F"}};
    };
};
