
#include "\z\misery\addons\anvil\ui\anvil.hpp"
#include "\z\misery\addons\compat_rearm\ui\rearmShop.hpp"
#include "\z\misery\addons\cooking\ui\cooking.hpp"
#include "\z\misery\addons\crafting\ui\crafting.hpp"
#include "\z\misery\addons\currency\ui\bank.hpp"
#include "\z\misery\addons\currency\ui\moneyGiveMenu.hpp"
#include "\z\misery\addons\currency\ui\moneyTakeMenu.hpp"
#include "\z\misery\addons\devils_luck\ui\devils_luck.hpp"
#include "\z\misery\addons\doorlocks\ui\doorLock.hpp"
#include "\z\misery\addons\fire\ui\fireCrafting.hpp"
#include "\z\misery\addons\fishing\ui\fishing.hpp"
#include "\z\misery\addons\forge\ui\forge.hpp"
#include "\z\misery\addons\fuel\ui\refill_fuelCan.hpp"
#include "\z\misery\addons\fuel\ui\refuelVehicle.hpp"
#include "\z\misery\addons\furniture\ui\furniture.hpp"
#include "\z\misery\addons\furniture\ui\vehicleFurniture.hpp"
#include "\z\misery\addons\generator\ui\generator.hpp"
#include "\z\misery\addons\hydrology\ui\hydrology.hpp"
#include "\z\misery\addons\inventory\ui\inventoryActions.hpp"
#include "\z\misery\addons\inventory\ui\inventoryFramework.hpp"
#include "\z\misery\addons\inventory\ui\inventoryText.hpp"
#include "\z\misery\addons\maintenance\ui\maintenance.hpp"
#include "\z\misery\addons\persistence\ui\grad_persistence.hpp"
#include "\z\misery\addons\refuel\ui\refuelShop.hpp"
#include "\z\misery\addons\repair\ui\repairShop.hpp"
#include "\z\misery\addons\sleep\ui\sleep.hpp"
#include "\z\misery\addons\traders\ui\traderShop.hpp"
#include "\z\misery\addons\treatment\ui\medicalTreatment.hpp"

class RscTitles {
    #include "\z\misery\addons\eru\ui\eru.hpp"
    #include "\z\misery\addons\geiger\ui\geiger.hpp"
    #include "\z\misery\addons\maintenance\ui\vehicleStats.hpp"
    #include "\z\misery\addons\overlays\ui\bloodShot_overlay.hpp"
    #include "\z\misery\addons\overlays\ui\tunnel_overlay.hpp"
};
